include theos/makefiles/common.mk

BUNDLE_NAME = AirplaneSignalToggle
AirplaneSignalToggle_FILES = Switch.x
AirplaneSignalToggle_FRAMEWORKS = UIKit
AirplaneSignalToggle_LIBRARIES = flipswitch
AirplaneSignalToggle_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk